### ISSUE TITLE
[Bug]: ransomlook module isn't installed

### ISSUE THREAD

**Issue by R3dHash** [RansomLook/RansomLook#120]
### What happened?

Upon a first installation attempt I got:
```sh
 File "/home/vboxuser/Documents/RansomLook/tools/3rdparty.py", line 5, in <module>
    from ransomlook.default import get_homedir
ModuleNotFoundError: No module named 'ransomlook'
```
via the command:
```sh
poetry run tools/3rdparty.py 
```
from /home/vboxuser/Documents/RansomLook/

it seems related to the fact that ransomlook was not installed upon "poetry install". If the command is trigerred with the defaut poetry.lock nothin happens. If I erase the file then the modules get installed but still not ransomlook.

**Comment by FafnerKeyZee** [comment]
Hey,

Sounds like there is an issue with Poetry.
What is the version of poetry you used ? (poetry -V)

BR,

**Comment by R3dHash** [comment]
Heyhey :),
Poetry version 1.4.0

BR,

**Comment by FafnerKeyZee** [comment]
Hey, 

I updated the project with poetry 1.4.0. there is no bug on my side.

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy

Poetry (version 1.4.0)

Can you retest please ?

BR,

**Comment by R3dHash** [comment]
I still have the issue apparently though I removed and recloned the project.
<img width="634" alt="screenshot" src="https://user-images.githubusercontent.com/97284989/225636234-d8f61c7e-aed7-4f5f-9850-18cb0ec62ad9.png">

I checked with 'head poetry.lock' that the version 1.4.0 was indeed present.

BR,

**Comment by FafnerKeyZee** [comment]
Can you run `poetry env info`  and delete the Path of the Virtualenv ?
![image](https://user-images.githubusercontent.com/11160904/225667825-0c6dc1e3-04e3-4fc4-b903-206fb05cafd4.png)
`/home/fafner/.cache/pypoetry/virtualenvs/ransomlook-N7Lmpcmc-py3.10` in my case

BR,

**Comment by R3dHash** [comment]
Yes :). This is what I got... 
<img width="718" alt="screenshot" src="https://user-images.githubusercontent.com/97284989/225711585-e6ec57ae-f786-4880-bd12-c7a83aaf1a94.png">

BR

**Comment by Rafiot** [comment]
And just making sure: this is a full screenshot of the `poetry install` output? It is way too short on your screenshot and should display everything that is installed.

**Comment by R3dHash** [comment]
In line with you @Rafiot but I don't get bette... no clue why ):

**Comment by Rafiot** [comment]
And what about `poetry install -v` ?

**Comment by R3dHash** [comment]
I had tried indeed but was not helping much unfortunately...
<img width="443" alt="screenshot" src="https://user-images.githubusercontent.com/97284989/225734340-84e13e01-c050-49d6-9f41-47a15e33f084.png">

**Comment by Rafiot** [comment]
There is something deeply weird with your setup and I have no idea where that's coming from. The path to the .venv is non-standard now, but was closer to what I would expect in your message just before.

Did you configure poetry somehow? But I'm sorry, I have no idea what is going on on your machine, this is how it should look:

![Screenshot_20230316_204851](https://user-images.githubusercontent.com/248875/225736534-c78c4d2e-fb98-43ee-af84-af3ee1ceb403.png)

**Comment by Rafiot** [comment]
wait a sec... You use sudo to clone the repository. Don't do that, your perms are broken.

delete the repository, clone as your normal user(without sudo) and it will work.

**Comment by FafnerKeyZee** [comment]
Hum, I do not like the venv used because it's a file, not a folder.

Did you used : ` curl -sSL https://install.python-poetry.org | python3 -`  to install poetry ? Or did you do some modifications ?
And to be honest I do not understand why you need to use `sudo` to clone or delete folders. 

BR,

**Comment by R3dHash** [comment]
In the meantime I had tried from a fresh install (1st snapshot after installation of Ubuntu) that didn't solve the problem and also without the sudo (I realized its unrelevant usage here I'm used to other OS), but the behavior was the same.
I used indeed curl -sSL https://install.python-poetry.org | python3 - 
and a reboot.

**Comment by R3dHash** [comment]
I did the same on a debian and it worked like a charm...

**Comment by FafnerKeyZee** [comment]
Considered as closed. Feel free to reopen it with more details if the bug is still there.
