### ISSUE TITLE
Add Local Admin for GUI 

### ISSUE THREAD

**Issue by SwaGBerlusconi94** [RansomLook/RansomLook#136]
### Notes

Hi , guys , how i add a local admin for enable the gui to add groups? Thanks.

**Comment by FafnerKeyZee** [comment]
Hello,

you have to set : "users" in generic.json

ex:
```
  "users": {
    "user1": "password1",
    "user2": "password2"
  },
```

**Comment by FafnerKeyZee** [comment]
Considered as closed. Feel free to reopen it with more details if needed.
