### ISSUE TITLE
[Feature]: Allow to export Crypto db

### ISSUE THREAD

**Issue by phdphuc** [RansomLook/RansomLook#143]
### Is your feature request related to a problem? Please describe.

[Code](https://github.com/RansomLook/RansomLook/blob/25d2c700b21c0cda9400f43ac6c44ac68cc58abd/website/web/__init__.py#L609)

### Describe the solution you'd like

Allow database '7' for crypto export.

**Comment by FafnerKeyZee** [comment]
Hey,

Should be fixed now :)

BR,
