### ISSUE TITLE
[Bug]: Screenshots do not work 404 error when using web interface 

### ISSUE THREAD

**Issue by dblaster** [RansomLook/RansomLook#171]
### What happened?

screenshots are in the source/screenshots folder but when using the web interface they do not resolve and display a 404 error. 

### If the issue is related to the web interface, what browsers are you seeing the problem on?

Chrome

**Comment by FafnerKeyZee** [comment]
I'm reopening the issue. Got some 404 error with telegram and Twitter. Will be fixed asap.
