### ISSUE TITLE
[Bug]: Telegram Bot Fails to Join Channels or Groups 

### ISSUE THREAD

**Issue by Ozer0x777** [RansomLook/RansomLook#178]
### What happened?

What happened?

I would like to report a bug regarding the Telegram bot's functionality. The bot is currently unable to join channels or groups when prompted with the "Join Channel" button. Additionally, it fails to link the button properly, preventing successful channel or group joining. I have attached a screenshot for reference.

![7662](https://github.com/RansomLook/RansomLook/assets/128625306/7a8accea-2c3c-4d0b-af36-0a74b5e4c16c)
![+5XrZvo1danNhOGEy](https://github.com/RansomLook/RansomLook/assets/128625306/6a060452-a0a1-4059-9b17-d9605dceb65d)

**Comment by FafnerKeyZee** [comment]
Hey,

Sorry for the moment Ransomlook only scan/parse open telegram chan, for monitoring private chan we need to use the API.
I'll take a look on it but I dunno when :(

BR;

**Comment by Ozer0x777** [comment]
I'll look at it on my side, if I come up with a functional code can I push it to you?

**Comment by FafnerKeyZee** [comment]
For sure, feel free to contribute to this project :)
