### ISSUE TITLE
New Group - cactus

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#197]
cactusbloguuodvqjmnzlwetjlpj6aggc6iocwhuupb47laukux7ckid.onion

**Comment by FafnerKeyZee** [comment]
It's already on the public website. 
I'll release a parser soon.

BR

**Comment by FafnerKeyZee** [comment]
Solved with: https://github.com/RansomLook/RansomLook/commit/719b1c0caacca819fc9b15e1f8691c80f75df795
