### ISSUE TITLE
[Feature]: Add Screenshots for Ransom posts

### ISSUE THREAD

**Issue by Stanley9990** [RansomLook/RansomLook#200]
### Is your feature request related to a problem? Please describe.

Screenshots at the moment are only incorporated for Ransomware Group pages.

### Describe the solution you'd like

I'd like to see a screenshot for each new post added to the site, not just for the group ransomware pages.

### Describe alternatives you've considered

ransomware.live incorporates this feature

### Additional context

N/A

**Comment by FafnerKeyZee** [comment]
Hello,

It's in the todolist, but need to check which is the best way to implement it.

Best regards

**Comment by Stanley9990** [comment]
Would love to have a look at it, could you point me towards where the current screenshot code is?

**Comment by FafnerKeyZee** [comment]
Hello,

Big news, work is in progress, I've to update all the parser to add the link for the post ;) I've a working parser for 'ransomed'. 

```
import os
from bs4 import BeautifulSoup

def main():
    list_div=[]
    for filename in os.listdir('source'):
        try:
            if filename.startswith(__name__.split('.')[-1]+'-'):
                html_doc='source/'+filename
                print(filename)
                file=open(html_doc,'r')
                soup=BeautifulSoup(file,'html.parser')
                div = soup.find('div')
                divs_name=div.find_all('a', {"style":"margin-bottom: 10px; color: #ccc; font-family: monospace; text-decoration: underline; cursor: pointer;"}) # type: ignore
                for a in divs_name:
                    list_div.append({"title": a.text.strip(), "description": "", "link": a['href'], "slug": filename})
                file.close()
        except:
            pass
    print(list_div)
    return list_div
``` 
So I hope switch all the active groups for the end of month ;)

**Comment by FafnerKeyZee** [comment]
I wrote a script to run in addition of `scrape` and `parse` : `screen`

**Comment by FafnerKeyZee** [comment]
Solve with last commit, still have to edit parsers ;)

**Comment by FafnerKeyZee** [comment]
Hey,

All parsers have been updated \o/
Can you confirm to me that it's ok on your side ?

Best regards,
