### ISSUE TITLE
Telegram channel

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#204]
Hello everyone! 

I've set up a Telegram channel featuring all the latest RansomLook posts. 
The content is sourced from the RansomLook Mastodon account. 

Feel free to join and share the channel: 

https://t.me/ransomlook

**Comment by ErezDasa** [comment]
Not sure what do you mean "open freely the chan"..  I made the channel public so anyone can join =)

**Comment by FafnerKeyZee** [comment]
and see it without having an account ?

**Comment by FafnerKeyZee** [comment]
Preview channel option:
t.me/s/ransomlook << should allow every one the check the chan

**Comment by ErezDasa** [comment]
Nice, didn't know that.
