### ISSUE TITLE
Ransomexx

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#214]
http://rnsm777cdsjrsdlbs4v5qoeppu3px6sb2igmh53jzrx7ipcrbjz5b2ad.onion/

**Comment by FafnerKeyZee** [comment]
Hey,

Sorry but I don't understand what do you mean with your link. There is already a parser for this blog: https://github.com/RansomLook/RansomLook/blob/main/ransomlook/parsers/ransomexx.py
And all data are correctly parsed: https://www.ransomlook.io/group/ransomexx
So please give me more information.

BR,

**Comment by ErezDasa** [comment]
Ohh sorry, I just searched for the last victim and didn't find it I'm the list (DVA - DVision Architecture) so I thought it's noe exist. Sorry my bad.
