### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aarti180920** [RansomLook/RansomLook#244]
I am not able to access telegram module without api and I can see raw data of cryptocurrencies but not able to see on the webpage panel 

_No response_

**Comment by FafnerKeyZee** [comment]
Hello,

I'm not sure to understand, 
* Which telegram module are you speaking ? In the official instance or in your own instance ?
* Where do you see the raw data of cryptocurrencies ? On redis ?
BR

**Comment by FafnerKeyZee** [comment]
No more details, we can closed the issue.
