### ISSUE TITLE
[Notes]: LEAKS???

### ISSUE THREAD

**Issue by ruoydnim** [RansomLook/RansomLook#245]
### Notes

pkease where i can download files from leaks?
https://www.ransomlook.io/leak/

**Comment by FafnerKeyZee** [comment]
Hello,

Leaks are not available to download. Notifications are from https://leak-lookup.com, but in most case they are easy to find ;-)

BR,

**Comment by ruoydnim** [comment]
when i  pay on that site can i check all mail:pass what have in our dbs?how? i think its only search mail:pass from all dbs not show mail:pass what is in db, sorry for my english

**Comment by FafnerKeyZee** [comment]
We do not store any data from leak in our DB .
We only monitor if new leaks are avaible. The information about columns are from the leak lookup
