### ISSUE TITLE
[Bug]: CORS preventing other sites/apps from using RansomLook API

### ISSUE THREAD

**Issue by htmalgae** [RansomLook/RansomLook#246]
### What happened?

The API you offer is amazing and I'd love to use it to build an alternative frontend for RansomLook.

Is there any way you could change the CORS rules so I could use it on different sites, eg. `localhost`?

Thank you so much!

### If the issue is related to the web interface, what browsers are you seeing the problem on?

Chrome

### Relevant log output

<img width="1039" alt="Screenshot 2023-10-04 at 8 25 36 AM" src="https://github.com/RansomLook/RansomLook/assets/145413421/8a353da4-3cb9-4682-84de-58a15abb5676">

**Comment by FafnerKeyZee** [comment]
Hello,

Thank you for your feedback.
Unfortunately we cannot disable CORS, not only for security reason but also regarding the possible overload on the public instance. We suggest trying one of the following possibilities:
* Run your own instance of RansomLook (you can easily import public instance data with the following script (`poetry run tools/import_from_instance.py` )
* Disable some security checks on your browser: (--disable-web-security for chrome / strict_origin_policy set to false for FireFox)

If you want to propose another frontend for RansomLook, or have some improvement suggestions, feel free to create a PR ;-)

**Comment by FafnerKeyZee** [comment]
No more details, we can closed the issue.
