### ISSUE TITLE
[Bug]:  I can't able to install

### ISSUE THREAD

**Issue by danger112233** [RansomLook/RansomLook#249]
### What happened?

A bug happened!

Hi bro,

First of all great thanks for creating this type of tools. Which is very useful in cyberspace..

The issue is I can't able to install this project ransom look I'm keep facing the portly installation even though as you said I installed Ubuntu 22.04 version on my Vmware could you plus help me on this..

I'm keep facing the issue on poetry instaltion

If you share the complete step of instaltion process that would be great for me.

My email: mohammed.askar332@gmail.com

**Comment by FafnerKeyZee** [comment]
Hello,

Without details about the error it's hard to help you.
To install poetry, run in a terminal the following command with the user who will run RansomLook:
`curl -sSL https://install.python-poetry.org | python3 -`
Then logout as explained during the install and log in again. Then try to run `poetry -V` with the user who have to run poetry. 

BR,

**Comment by danger112233** [comment]
![IMG-20231009-WA0008](https://github.com/RansomLook/RansomLook/assets/63256615/0f6dc60b-c9c0-4ef7-9c6d-59bbd7c16cb7)

PFA, as you said in above msg tried same but still facing the issue

**Comment by FafnerKeyZee** [comment]
Hey,

Looks like Poetry was already on the system. Are you using Kali ?
If yes it could explain the behavior because Kali already embeds another version of poetry.

BR,

**Comment by danger112233** [comment]
Im using Ubuntu 22.04

**Comment by FafnerKeyZee** [comment]
What is the results of
whichis poetry
?

But to be honest it looks like there is another poetry installed. So better to open a bug on poetry repo

**Comment by icepaule** [comment]
Hi danger,

I had some issues with poetry as well.
All my problem were fixed from completly removeing poetry and reinstalling it as per the doc provided.
pip3 uninstall poetry
pip uninstall poetry
apt purge poetry
apt purge python3-poetry

Then reinstall as per HowTo: https://python-poetry.org/docs/

apt install pipx
pipx install poetry
pipx ensurepath

Aftre that "poetry install" worked like a charm.  ;-)
