### ISSUE TITLE
[Feature]: Feed RSS of recent post

### ISSUE THREAD

**Issue by drego85** [RansomLook/RansomLook#261]
### Is your feature request related to a problem? Please describe.

Hi,
I think it would be very useful to have an RSS feed of the 'Recent Post' section so that we can better follow the project.

Thanks

### Describe the solution you'd like

ND

**Comment by FafnerKeyZee** [comment]
Hello,

I'll try to do a RSS Feed, what did you except to see in ?

BR,

**Comment by FafnerKeyZee** [comment]
Hey,

Can you check there: https://www.ransomlook.io/rss.xml
with this commit: 13be1084a433a7d41ef78f651e7ef926eb5a6b1d

**Comment by drego85** [comment]
Hi, sorry for the delay. I had not seen your previous message.

I think you have introduced the most important information into the RSS feed, great!

However, I did a check with W3C's Feed Validator tool and unfortunately several errors were found: `https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.ransomlook.io%2Frss.xml` 

First of all, I think there are too many entries, usually an RSS feed has 10 or 20 entries. Here we have about 11 thousand :)

Thanks you for this new features ;)

**Comment by FafnerKeyZee** [comment]
Oopsie, 
I didn't seen to right dict :) For the moment it's set to 50.
And it should be validated, except for guid but we know why ;)

**Comment by drego85** [comment]
Spectacular, thank you very much. It's perfect now!

**Comment by Tichod** [comment]
Great. Was expecting that for some time. Thumbs up!
