### ISSUE TITLE
Configuration Error with Groups in pyproject.toml

### ISSUE THREAD

**Issue by VicoLeChips** [RansomLook/RansomLook#271]
## Environment

- **OS**: Ubuntu 22.04.3 LTS
- **Poetry version**: 1.1.12

### Description

While running "poetry install" I get the following error: The Poetry configuration is invalid: - Additional properties are not allowed ('group' was unexpected)

![image](https://github.com/RansomLook/RansomLook/assets/62722776/246ed1ad-28fe-4e21-bcef-fe965ffde65d)

**Comment by FafnerKeyZee** [comment]
Hello,

Your poetry version is outdated, can you update it ? To 1.6.1 at least.

BR,
