### ISSUE TITLE
Inconsistent Capture of Ransomware Victim Data

### ISSUE THREAD

**Issue by VicoLeChips** [RansomLook/RansomLook#272]
The application is intended to monitor ransomware groups and markets, extracting details of their victims. I can see that on RansomWatch and RansomLook it just recently captured "villanuevadelaserena.es". Even after re-running the scrape commands on my instance and waiting for it to get through, I do capture an updated screenshot of their website (ransomware group). However, it does not get into my "recent post". Going into my logs it shows the following error: "Unable to retrieve the content because the page is navigating and changing the content".

![image](https://github.com/RansomLook/RansomLook/assets/62722776/638ebe5b-3268-420d-a3c8-b7fc75643f93)

**Comment by FafnerKeyZee** [comment]
What happens when you run
`poetry run parse `
?
Or all captures are in error ?

**Comment by FafnerKeyZee** [comment]
And you have to run
`poetry run screen` 
To get screen for the posts.
