### ISSUE TITLE
DragonForce rss feed

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#279]
For some reason DragonForce victims are not appearing in the rss feed.

Thanks!

**Comment by FafnerKeyZee** [comment]
Hello,
That's weird because I saw them on the public instance and my dev instance.

Do you have any logs ?

BR,

**Comment by ErezDasa** [comment]
Hi @FafnerKeyZee, I'm using feedly application with this rss url

Ransomlook.io/rss.xml

I only see 8 victims from the last 24 hours

**Comment by FafnerKeyZee** [comment]
Hummmm ,

If you try to access it in your browser you should see them.
Will try to investigate why you can't see them in your reader

**Comment by ErezDasa** [comment]
Thank you!

**Comment by FafnerKeyZee** [comment]
Hey!
good news I guest, sound that it's working fine for feedly now. will push the change on github today, but already running on the public instance
Feedly needs  guid to work properly ;)

BR,

**Comment by ErezDasa** [comment]
Awesome, thanks!

**Comment by FafnerKeyZee** [comment]
Fixed with : https://github.com/RansomLook/RansomLook/commit/e245765cbb0c54b7915db3fed9d78456dc36e438

Could have a few overlaps on feedly on the next check due to the change of guid ;)
