### ISSUE TITLE
[Notes]: new group - Slug

### ISSUE THREAD

**Issue by GossiTheDog** [RansomLook/RansomLook#301]
### Notes

http://3ytm3d25hfzvbylkxiwyqmpvzys5of7l4pbosm7ol7czlkplgukjq6yd.onion

**Comment by FafnerKeyZee** [comment]
Hello,

Was done before I saw your issue :)

https://github.com/RansomLook/RansomLook/commit/3f1a2c077e7bc6bebc30716a53770d3c5592d797
https://www.ransomlook.io/group/slug

BR,
