### ISSUE TITLE
[Feature]: Auth SMTP + SSL

### ISSUE THREAD

**Issue by R3dHash** [RansomLook/RansomLook#302]
### Is your feature request related to a problem? Please describe.

Once Ransomlook is not installed into an enterprise perimeter it would be handy to send emails througout a dedicated gmail account for instance to ensure the incoming emails are not vetted as spams.

### Describe the solution you'd like

For this are required additional fields for authentication and SSL encryption.
 ``` Bash 
server = smtplib.SMTP_SSL(config['smtp_server'],config['smtp_port'])
server.login(config['smtp_login'],config['smtp_password'])
server.send_message(msg)
```
then one has to add those two fields in the file generic.json:
 ``` Bash 
 "smtp_login": "email@gmail.com",
 "smtp_password": "superpassword",
```

An ssl boolean could redirect to the expected smtp lib

Best,

**Comment by FafnerKeyZee** [comment]
Hey,

I'll try to do it ASAP.

BR,

**Comment by FafnerKeyZee** [comment]
Should be fixed with last commit :) https://github.com/RansomLook/RansomLook/commit/b8aa0b9aab12a898dbeb2c98b6a309fc79457d06
