### ISSUE TITLE
Question about: generic.json

### ISSUE THREAD

**Issue by wabass** [RansomLook/RansomLook#325]
```
With the default configuration, you can access the web interface on http://0.0.0.0:8000.
```
What if we set it on public IP.

Which part in generic.json we would set it?
Apologies for this cause, I tried all the "_notes" infos. 

Especially the:
```
"siteurl":
and
"website_listen_ip"
```

And seems my visible public IP wont shoy any. But error ERR_CONNECTION_REFUSED

**Comment by FafnerKeyZee** [comment]
Hello,

"siteurl" is used for some internal tools, like email, and referer links.

If you want to expose it for internal used; you can set :
  "website_listen_ip": "0.0.0.0",
  "website_listen_port": 8000
and access to it via http://yourinternalIP:8000

If you want to expose it on internet, it's better to set
  "website_listen_ip": "127.0.0.1",
  "website_listen_port": 8000
and then use nginx or apache as proxy for better security ;)
