### ISSUE TITLE
[Bug]: poetry run start command doesn't finish

### ISSUE THREAD

**Issue by liamhess** [RansomLook/RansomLook#362]
### What happened?

Heyhey,
I'm trying to host my own instance but for some reason I can't figure out the `poetry run start` command never finishes.
I am running the instance on relatively low resources with only 2 cores so this might be the reason
But also the site seems to function fine, so it might not even be a problem, just wanted to check :)
<img width="846" alt="image" src="https://github.com/RansomLook/RansomLook/assets/49128538/2917d2a9-08eb-48c7-a68b-297cfcc0e2fc">
I've let it run for an hour at least now and it still looks like this.

Best regards,
Liam :)

**Comment by liamhess** [comment]
Yes exactly, i'm perfectly able to access everything on the website, I was just not sure if the command was supposed to finish, as there is a `stop` command
But thanks a lot for the quick answer!
Regards :)

**Comment by FafnerKeyZee** [comment]
Hello,

Command is finished ;-)
Just because the output is in tty, you saw all the messages, but if you check closer after:
```
done.
start website
done.

```
You can see you terminal input.

Br,

**Comment by liamhess** [comment]
Ooh, yes makes sense, thanks a lot for pointing it out :)
