### ISSUE TITLE
[Feature]: Searching for keywords in ransom notes.

### ISSUE THREAD

**Issue by PinkCursor** [RansomLook/RansomLook#363]
### Is your feature request related to a problem? Please describe.

We should have the ability to search the ransom notes on ransomlook.io/notes.

### Describe the solution you'd like

Results of ransom notes should show in ransomlook.io/search

**Comment by FafnerKeyZee** [comment]
Shoud be fixed with: https://github.com/RansomLook/RansomLook/commit/f38d045d51a91fd23f73fa26303cf3debcc79c57
