### ISSUE TITLE
[Bug]: libgdk-pixbuf-2.0-0

### ISSUE THREAD

**Issue by etaylor77** [RansomLook/RansomLook#381]
### What happened?

I am struggling to figure out a proper/current version this repository. 

Currently running Ubuntu 20.04.6 LTS

### Relevant log output

```shell
E: Unable to locate package libgdk-pixbuf-2.0-0
E: Couldn't find any package by glob 'libgdk-pixbuf-2.0-0'
```

**Comment by etaylor77** [comment]
I see the issue as a typo. The package is:  libgdk-pixbuf2.0-0

Please update the command as follows:

sudo apt install libgtk-3-0 libpangocairo-1.0-0 libcairo-gobject2 libgdk-pixbuf2.0-0 libx11-xcb1 libxcursor1

**Comment by FafnerKeyZee** [comment]
Hello,

I did not test with ubuntu 20.X I only support 22.X and will start to support for 24.X soon.
As both package are available on 22.X, I'll do change in doc.
![image](https://github.com/RansomLook/RansomLook/assets/11160904/2af5fdc0-2227-4e2a-bfb0-d9d59766886d)

Thanks for the bug.

**Comment by FafnerKeyZee** [comment]
https://github.com/RansomLook/RansomLook/commit/08f22488aa024598bc75fcbdc757204f6c53ddc4
