### ISSUE TITLE
TypeError when trying to run malpedia.py

### ISSUE THREAD

**Issue by repolaa** [RansomLook/RansomLook#39]
I'm following the steps described in the install guide on the README but when I try to populate descriptions and profiles from Malpedia by running `poetry run tools/malpedia.py` I get a TypeError.

Full output is:
```bash
Traceback (most recent call last):
  File "/home/antonio/RansomLook/tools/malpedia.py", line 19, in <module>
    names.append(families[family]['common_name'])
TypeError: string indices must be integers
```

I'm using Lubuntu 22.04.1 LTS x86_64. Also tried on Ubuntu, same version.

**Comment by FafnerKeyZee** [comment]
Hello,

It looks like you don't have a valid api key for malpedia. Did you set it in config/generic.json ?
Will add some check tomorrow on the script.

BR,

**Comment by FafnerKeyZee** [comment]
I did a fix on malpedia.py.
https://github.com/RansomLook/RansomLook/commit/d2661a5806a3861f98fc0c34456f1172c0ce4575
