### ISSUE TITLE
RANSOMCORTEX

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#391]
http://gg6owuhu72muoelkt2msjrp2llwr2on5634sk5v2xefzmobvryywbhid.onion

**Comment by FafnerKeyZee** [comment]
HEllo,

Thanks for the link.
Parser is ok: https://github.com/RansomLook/RansomLook/commit/96c6c548a3f61e0839e3c2938b9e31ed3075cb06
And public instance uptodate: https://www.ransomlook.io/group/ransomcortex
