### ISSUE TITLE
[Feature]: Add ARCUS MEDIA

### ISSUE THREAD

**Issue by etaylor77** [RansomLook/RansomLook#405]
### Is your feature request related to a problem? Please describe.

Add new threat actor group

### Describe the solution you'd like

Add parser for: http://arcuufpr5xxbbkin4mlidt7itmr6znlppk63jbtkeguuhszmc5g7qdyd.onion/

**Comment by FafnerKeyZee** [comment]
Hello,

Worker is up and on the repo:  https://github.com/RansomLook/RansomLook/blob/main/ransomlook/parsers/arcus%20media.py
Can you please describe what you need/want ?

BR

**Comment by etaylor77** [comment]
This one and FOG is not showing any posts.

**Comment by FafnerKeyZee** [comment]
That's pretty weird because I got them in my dev, private and public instance.
Can you give me the url you used please ? can you share the content of the source ? located in %RANSOMLOOK%/source/arcus media-XXXXX

BR

**Comment by etaylor77** [comment]
It was an issue on my side, sorry about that.
