### ISSUE TITLE
Lynx group

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#410]
http://lynxbllrfr5262yvbgtqoyq76s7mpztcqkv6tjjxgpilpma7nyoeohyd.onion/disclosures

http://lynxblog.net/leaks

**Comment by FafnerKeyZee** [comment]
Hello,
We added it on public instance, but we have to debug scraping before creating the parse
Regards

**Comment by FafnerKeyZee** [comment]
Working on public instance. But you have to install the last commit
