### ISSUE TITLE
Image in rss feed?

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#424]
Hi, is there any option to add the DLS post image to the rss feed?

**Comment by FafnerKeyZee** [comment]
Hum dunno how I can do it, but I'll check...

**Comment by FafnerKeyZee** [comment]
should be solved with: https://github.com/RansomLook/RansomLook/commit/b8446845177418eb2847d748822203577765793f
Can you confirm is it working for you ? (it's running in public instance)

**Comment by FafnerKeyZee** [comment]
Can you contact us at our mail ;-) in doc or about, for the tg Chan please ?Envoyé de mon iPhoneLe 26 oct. 2024 à 18:07, ErezDasa ***@***.***> a écrit :﻿
It's working. Thanks!
I'll add it to the tg cahnnel
