### ISSUE TITLE
Valencia group

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#430]
https://6doyqxqqj36vnedtt2zwxmngx52mgyp7brbrtwkyd75jgiolocoybgid.onion/

**Comment by FafnerKeyZee** [comment]
Hello,

Thanks for sharing, but site looks down :'(

**Comment by FafnerKeyZee** [comment]
Ok, I create the entry on the public instance, as soon as the website is up and  scraped by the scraper, I'll create a parser :)
