### ISSUE TITLE
[Feature]: Add New Fileserver URL section on group profiles

### ISSUE THREAD

**Issue by PinkCursor** [RansomLook/RansomLook#453]
### Is your feature request related to a problem? Please describe.

Fileserver urls are taking a lot of space in the default url section of group profiles.

### Describe the solution you'd like

We are currently adding a lot of current and older fileserver addresses to Ransomlook and they are all collected under the URL section in the group's profiles.

**Comment by FafnerKeyZee** [comment]
Down with last commit!
https://github.com/RansomLook/RansomLook/commit/71c1d452d68c17fd8f07a9b3dc0d71df778ccb46
