### ISSUE TITLE
[Bug]: Scraper Issue on Production - Onion Links Not Displaying as Online

### ISSUE THREAD

**Issue by VicoLeChips** [RansomLook/RansomLook#468]
### What happened?

No onion links appear as "online" when accessing the "/alive" endpoint on the production environment at https://www.ransomlook.io/alive.

**Comment by FafnerKeyZee** [comment]
it's working like a charm for me....
![image](https://github.com/user-attachments/assets/620ebf9f-f98b-4bbd-b59b-bea236e1aa81)
