### ISSUE TITLE
Safepay

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#489]
nz4z6ruzcekriti5cjjiiylzvrmysyqwibxztk6voem4trtx7gstpjid.onion

**Comment by FafnerKeyZee** [comment]
Hello,

Thanks you,
We already have the dls but weren't able to see it online :/https://www.ransomlook.io/group/safepay

**Comment by FafnerKeyZee** [comment]
My bad, we had the other one. Get it working, so except a worker and a parsing on public instance for next run ;)

**Comment by FafnerKeyZee** [comment]
https://github.com/RansomLook/RansomLook/commit/10cbd0ace33ab1137ebf1108b9141ea5dbb13dfd
