### ISSUE TITLE
[Bug]: Termite parser not extracting links despite visible in screenshots

### ISSUE THREAD

**Issue by 1c3z** [RansomLook/RansomLook#493]
I've noticed a discrepancy in the Termite group data collection:
- The screenshots show victim links are visible on the page
- However, these links are not appearing in the parsed results

![image](https://github.com/user-attachments/assets/2ed60fde-fe4d-4723-903b-87ab41efed29)
![image](https://github.com/user-attachments/assets/1f870e42-58d7-40e4-b751-f7c8193ba8b9)

This suggests there might be an issue with the parser logic rather than a page loading problem. Could you please check:
1. If the parser (BeautifulSoup) is correctly targeting the HTML elements containing the links
2. If the link extraction pattern matches the current page structure

This would help ensure we're capturing all available data from the Termite group.

Let me know if you need me to provide any screenshots or additional details.

Thank you!

**Comment by FafnerKeyZee** [comment]
Hello,

It looks that it's running correctly in public instance.
https://www.ransomlook.io/group/termite
We can see all posts.. So I'm not  sure  to really understand your request/bug

Br,

**Comment by 1c3z** [comment]
Thanks for checking. My mistake - I misunderstood how it works.
