### ISSUE TITLE
[Bug]: For the API - /api/last - getting Internal Server Error

### ISSUE THREAD

**Issue by jacksparrow025** [RansomLook/RansomLook#495]
### What happened?

For the Api endpoint /api/last - getting Internal Error.
![Screenshot 2024-11-26 at 8 12 28 PM](https://github.com/user-attachments/assets/2f3f1d44-f9c1-48b3-950b-05e03b5b1c71)

### Relevant log output

```shell
Screen shot attached 
{
  "message": "Internal Server Error"
}
```

**Comment by FafnerKeyZee** [comment]
Hello,

Thanks you it's fixed with https://github.com/RansomLook/RansomLook/commit/7e18c7b263acfb35cbfbaf3dabb9f89570431476 . 

Br
