### ISSUE TITLE
Funksec group

### ISSUE THREAD

**Issue by ErezDasa** [RansomLook/RansomLook#500]
http://7ixfdvqb4eaju5lzj4gg76kwlrxg4ugqpuog5oqkkmgfyn33h527oyyd.onion

**Comment by FafnerKeyZee** [comment]
Yep we spot it last night ;-)

https://www.ransomlook.io/group/funksec

We will add the parser on the repo today and unlock the dls on the public instance

BR,

**Comment by FafnerKeyZee** [comment]
https://github.com/RansomLook/RansomLook/commit/2f000f6a5e4f794936194dd7296d2e0fe0c2c471
