### ISSUE TITLE
[Bug]: "Last visit" and / or  "Available" Inaccurate 

### ISSUE THREAD

**Issue by VicoLeChips** [RansomLook/RansomLook#515]
### What happened?

The "Last Visit" and / or "Available" variable(s) on the official website do not seem to be accurate. For instance, for the group FunkSec, on RansomLook, it does show that the website is not available (which it is actually reachable and available at the time of this message) and that RansomLook has not reached FunkSec for over a week now:
![image](https://github.com/user-attachments/assets/314563ba-6a13-4354-9fbd-6fdcceab072f)

However, when navigating to the group details on RansomLook (https://www.ransomlook.io/group/funksec), it shows new victims that have been scraped within the last 24 hours:
![image](https://github.com/user-attachments/assets/67e4ba15-0e19-4f7d-a0b3-8c55cf81e19b)

Many issues arise, especially that if it managed to parse new victims within the last 24 hours, it means that it managed to reach out the website. Therefore, neither the date of last visit and the "availability" variables are correct.

**Comment by FafnerKeyZee** [comment]
Hello,

We are in the case where the har isn't created by Lacus...

As we don't use it anyway, I should change this part of the code and only validate on the html  or screenshot file.

BR

**Comment by FafnerKeyZee** [comment]
fixed with: https://github.com/RansomLook/RansomLook/commit/b5d21a2e18b8da2d3a2599ca0adfe32f92d9a7ee
